image: ghcr.io/gitpod-io/workspace-full:latest

ports:
  - port: 3000
    onOpen: ignore
  - port: 7007
    onOpen: ignore

tasks:
  - name: Install
    init: |
      nvm use 18
      corepack enable
      yarn install --frozen-lockfile
  - name: Dev
    command: |
      nvm use 18
      yarn dev
  - name: Open UI
    command: gp await-port 3000 && gp preview "$(gp url 3000)/aika-onboarding"
